version: "3.3"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: hamster
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  login_api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
      - ./.env:/usr/src/app/.env
    ports:
      - "81:3000"
    depends_on:
      - "db"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "80:3000"
    depends_on:
      - "login_api"
