version: "3.3"

services:
  hamster_db:
    image: mariadb:10.5.8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: hamster
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    depends_on:
      - hamster_db
    image: arm64v8/phpmyadmin
    restart: always
    ports:
      - '8082:80'
    environment:
      PMA_HOST: hamster_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  login_api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
      - ./.env:/usr/src/app/.env
    ports:
      - "3001:3000"
    depends_on:
      - "hamster_db"

  data_api:
    build: ./dataAPI
    volumes:
      - ./dataAPI:/usr/src/app
      - ./.env:/usr/src/app/.env
    ports:
      - "3002:3000"
    depends_on:
      - "hamster_db"
  
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - "login_api"
