version: "3.3"

services:
  bookflix_db:
    image: mariadb:10.5.8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: bookflix
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    depends_on:
      - bookflix_db
    image: arm64v8/phpmyadmin
    restart: always
    ports:
      - '9082:80'
    environment:
      PMA_HOST: bookflix_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  login_api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
      - ./.env:/usr/src/app/.env
    ports:
      - "4001:3000"
    depends_on:
      - "bookflix_db"
 
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "4000:3000"
    depends_on:
      - "login_api"
